### PR TITLE
Add more explanations what to put

### PR DESCRIPTION
**Pull request by koppor**
Coming from the templates at https://github.com/joelparkerhenderson/architecture_decision_record, I find it quite nice to have some more text indicating what to do.

I agree that users often working with ADRs should really know what to put.
In case newbies are using the tool, more text could help.

### CODE REVIEW

**Comment by koppor** [comment]
May I ask what I can to do get this merged?

**Comment by retnuh** [comment]
At a guess, do a `make check` and see if there is a failing test; you may need to fix the expected output to match your changes.

**Comment by koppor** [comment]
@retnuh Thank you for the hint! I needed to patch adr-new, too. 😇

**Comment by koppor** [comment]
The tests pass, seems to be good from my side. May I ask whether you see something that I missed?

**Comment by npryce** [comment]
I'm conflicted about this.

On the one hand, it's useful for newbies, as you say.

But on the other, after a short time it becomes annoying, because you have to delete lots of boilerplate text to get started when writing a new ADR.

The tool already allows you to add a different template to your ADR directory (create a file called `template.md`). So if you find that your team needs more instructions, you can create a template in your project for them.

**Comment by retnuh** [comment]
One could argue, then, that the default template should be the one most helpful to new users; and the advanced/experienced users would be savvy enough to change the template...

**Comment by koppor** [comment]
Is it about the double click to select a single word and quickly overwrite it?

grafik

I have kept the things a **single line**. Is it OK to assume that users know to go to first column and press <kbd>Shift</kbd>+<kbd>Cursor Down</kbd> and then start typing to replace a single line. OK, emacs users cann press <kbd>Ctrl</kbd>+<kbd>K</kbd> to delete a line and in IntelliJ it's also different. But I think, most advanced users know how to delete a single line.

**Comment by koppor** [comment]
My motivation for the change was that I did not know the list of status allowed and I wanted to have list to choose from. Not sure whether I will know all possible status when having created 100 ADRs.

**Comment by npryce** [comment]
@koppor the things you've identified as "one word" are template placeholders that are automatically replaced by the adr-tool.  A user would never see the hint for the title, except as unwanted text added after the title they have already input on the command line.

Also, there is no fixed list of statuses.  It's up to projects to choose statuses that match their process.  The tool manages status through command-line arguments and the user normally does not need to set the status by editing the file.  (That is the main point of this tool -- to manage the links in the Status sections of related ADR documents)

**Comment by koppor** [comment]
@npryce Yeah, I am still used to copy and paste the template manually. E.g., using GitHub's "New file" functionality.

I will backport your clarifications to https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md.

Thank you for still putting energy in this!

**Comment by npryce** [comment]
I've pushed a comment that adds more explanation to the template.

**Pull request closed without merging**
