### PR TITLE
Brew works against this repo

### LINKED ISSUE #24: Brew command on INSTALL.md does not work
On the [INSTALL.md](https://github.com/npryce/adr-tools/blob/master/INSTALL.md), it states that this can be installed with `brew install olleolleolle/adr-tools/adr_tools`, but this throws the error:
```
Error: inreplace failed
src/adr-init:
  expected replacement of "/usr/local/Cellar/adr_tools/2.0.0/config.sh" with "/usr/local/Cellar/adr_tools/2.0.0/bin/config.sh"
```

I'm guessing this is due to `config.sh` being removed in `2.0.0`. It might be worth removing the brew command, or linking to a working variant? I think there is a working tap by @olleolleolle https://github.com/olleolleolle/homebrew-adr-tools. I've not tried it though, so maybe it doesn't.

### PR DESCRIPTION
**Pull request by chids**
I just ran `brew install npryce/adr-tools/adr_tools` which worked so I just _assume_ it's legit... 🙈 

closes #24

### CODE REVIEW

**Comment by olleolleolle** [comment]
@chids Yayayay!

**Comment by chids** [comment]
🆗, so that was I tad bit naive. It works because https://github.com/npryce/homebrew-adr-tools/ exists. Ergo, `brew install npryce/adr-tools/adr_tools` currently installs `1.1.0`.

**Comment by olleolleolle** [comment]
If you care to prepare a patch towards the homebrew-adr-tools thing which makes it install 2.0, that would be grand.

**Comment by chids** [comment]
I started chids/homebrew-adr-tools@cee0a8044f3c512d6a3cfa488c415cb962aa29a5 but when I tested it something in Homebrew-land 💣'ed...
```
brew install chids/adr-tools/adr_tools                                                                        !4229
Updating Homebrew...
==> Installing adr_tools from chids/adr-tools
==> Downloading https://codeload.github.com/npryce/adr-tools/tar.gz/2.1.0
Already downloaded: /Users/chids/Library/Caches/Homebrew/adr_tools-2.1.0.0
Error: inreplace failed
src/adr-new:
  expected replacement of "ADR_TEMPLATE:-$(dirname $0)/template.md" with "ADR_TEMPLATE:-/usr/local/Cellar/adr_tools/2.1.0/template.md"
```
...and I only had limited time available which wasn't sufficient to prime my brain with enough Google to understand what the actual problem is.

**Comment by olleolleolle** [comment]
Yes, there are a few `inreplace`s that we have to do to live well in the land of homebrew directory layouts.

**Comment by npryce** [comment]
I've deleted my fork of homebrew-adr-tools

**Comment by fhemberger** [comment]
Meh. Just tried to install from this repo via homebrew:

```
brew install npryce/adr-tools/adr_tools

==> Tapping npryce/adr-tools
Cloning into '/usr/local/Homebrew/Library/Taps/npryce/homebrew-adr-tools'...
remote: Repository not found.
fatal: repository 'https://github.com/npryce/homebrew-adr-tools/' not found
Error: Failure while executing: git clone https://github.com/npryce/homebrew-adr-tools /usr/local/Homebrew/Library/Taps/npryce/homebrew-adr-tools --depth=1
```

**Comment by kevinjalbert** [comment]
Any update on this? Seems like the recommended approach for installing with brew installs version 1.2.0, while were on release 2.1.0 now.

**Comment by npryce** [comment]
@kevinjalbert See https://github.com/npryce/adr-tools/blob/master/doc/adr/0006-packaging-and-distribution-in-other-version-control-repositories.md -- I don't want to maintain packaging and distribution in the repo.  This PR was incorrect, and I'm closing it.

You'll have to ask about upgrading ADR Tools in Homebrew in the https://github.com/olleolleolle/homebrew-adr-tools project.

**Comment by kevinjalbert** [comment]
Makes sense. Thanks for the explanation.

**Pull request closed without merging**
