### PR TITLE
All files should have LF as newline separator

### PR DESCRIPTION
**Pull request by koppor**
This PR ensures that one can smoothly develop on Windows, because all files are checked out using LF line ending.

### CODE REVIEW

**Comment by MartyLake** [comment]
Isn't it an issue with how your git is configured ? do you know how core.autocrlf works ? https://help.github.com/articles/dealing-with-line-endings/#platform-windows

**Comment by koppor** [comment]
This thing ensures that the checkout is independent of someones git config.

`core.autocrlf true` makes the files having `CRLF` line endings, which prevents them being executed at `git bash`. With this PR, `git bash` on Windows is capable to execute the scripts.

**Comment by koppor** [comment]
I think, shell scripts (`.sh`) should always have `LF` endings. I think, the introduced change is minimal. Now that Notepad can deal with `LF` line endings (https://blogs.msdn.microsoft.com/commandline/2018/05/08/extended-eol-in-notepad/) and this configuration does not "hurt" Linux users, I would like to ask whether it is possible to re-consider this PR.

**Comment by npryce** [comment]
What tool uses the .editorconfig file? I have no way of testing this and ensuring it stays working because I don't have a Windows PC.

Is this to ensure that the adr-tool can run on Windows when checked out from source control?

If so, I feel this should be dealt with by a downstream packaging/distribution project that packages the tool for Windows (as the homebrew project packages it for MacOS).

**Comment by koppor** [comment]
> Is this to ensure that the adr-tool can run on Windows when checked out from source control?

This is done by `.gitattributes`.

The `.editorconfig` helps when editing files. And when creating new files. At dump IDEs, new files on Windows have `CRLF` as line endings, even though bash on Windows also likes LF more than CRLF. Because `.sh` scripts are always having `LF` as line endings.

> What tool uses the .editorconfig file?

Taken from https://editorconfig.org/:

grafik

grafik


One could also merge the `.gitattributes` change only. Thereby, one accepts that there might be space vs. tab issues.

All in all, I agree that `.editorconfig` is useful for newcomers and since there are not that many PRs, that support (a single file in the repo unknown to the maintainers) is really worth it.

**Comment by npryce** [comment]
So this is for people who want to hack on the code?  Not for end users?

If so, you can ignore my comment about packaging  for Windows.
And also, I am less worried about the testing aspects.

**Pull request merged**
