### PR TITLE
Add decisions dir to toc paths

### LINKED ISSUE #44: Add decisions dir to TOC paths
I'd like to output the TOC to an MD file on root of project, but links to the MD files are made so that file would have to be in the decisions dir itself.

I.e.

    * [1. Record architecture decisions](0001-record-architecture-decisions.md)

I'd like a flag in `generate toc` to generate links with the decisions dir added, or perhaps relative to the current folder, or as a string to prefix every path. Which (if any) do you prefer?

I.e.

    * [1. Record architecture decisions](decisions/0001-record-architecture-decisions.md)

(and thanks for making the tool, it's fun and useful :)

### PR DESCRIPTION
**Pull request by sephlietz**
I chose, I think, the easiest way to implement first, and probably the most commonly useful.

Closes #44

### CODE REVIEW

**Comment by npryce** [comment]
Could you make it so that the relative directory was passed as an argument of the `-r` option?

The `adr generate toc` command is used as part of a documentation build pipeline, and so the relative location of the ADR files and the TOC are usually unrelated to the source directory structure.

**Comment by sephlietz** [comment]
@npryce Done.

**Comment by npryce** [comment]
Thanks.

**Comment by gaggle** [comment]
Has this been released yet? I'm using latest version 2.1.0.

**Comment by npryce** [comment]
Ah... I tagged 2.2.0 but that doesn’t  make a release appear in GitHub. You can download the tag as a tar.gz file from the Tags tab until I configure the release in the GitHub UI

**Comment by npryce** [comment]
I've created release 2.2.0 now.

**Pull request merged**
